### ISSUE TITLE
Multisite Support

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/S3-Uploads#1]
The docs suggest Delicious Brains Offload plugin for multisite support, but our instance is now too large, and their plugin admin panel doesn't render, blocking us from further configuration. There are a couple of issues suggesting that Multisite is possible using this plugin. One key difference is the URL pattern in the bucket, which contains a site ID. The current pattern used by Delicious Brains is: 

https://s3.amazonaws.com/hwdsbcommons/wp-content/uploads/sites/12947/2019/03/image_name.jpeg

where 12947 is the site ID. 

Matching the upload path to the correct subsite directory in the S3 Bucket is our first stumbling block to moving over to this plugin.

**Comment by r-a-y** [comment]
We might want to check out a similar issue filed in the main repo - https://github.com/humanmade/S3-Uploads/pull/214

Specifically, there is a code snippet that enables multisite support - https://github.com/humanmade/S3-Uploads/pull/214#issuecomment-357255155

This doesn't address the URL pattern.  On the dev server, can you set up Delicious Brains and do a few test uploads, and then enable the Human Made plugin?  Then, I can see what I can do to match the Delicious Brains URLs.

**Comment by mrjarbenne** [comment]
Ok. Both plugins are now available on staging. I'm using RC2 of the S3-Uploads plugin. 

I uploaded an image using the DB plugin to this post: https://hwdsb.staging.boreal321.com/2019/05/06/a-photo-upload-to-db-s3/

Deactivated the DB plugin, activated the HM plugin, and uploaded an image here: 
https://hwdsb.staging.boreal321.com/2019/05/06/another-hm-s3-upload/

Once the DB plugin is deactivated, the images uploaded from that plugin break. If we can't match the URL structure exactly, as long as images uploaded before the migration work, the URL structure could change.

I haven't added the Multisite snippet from your comment above yet. Those examples are uploaded to the main domain. 

Here's one to the subdomain: https://test2.hwdsb.staging.boreal321.com/2019/05/06/a-test-on-a-subdomain-for-hm-s3/

With the current default settings of the HM plugin, images are all getting uploaded directly to commonstaging/uploads/"year"/"month" rather than breaking out into site specific directories. 

![2019-05-06_17-55-12](https://user-images.githubusercontent.com/480667/57257723-3e6f6000-7028-11e9-829c-6ece98fcfa78.png)

Deleting an image, uploaded to the main domain, removes it from the bucket appropriately.

**Comment by r-a-y** [comment]
I'm just taking a look at this and the image on the `test2` site appears to use the same URL pattern as the Delicious Brains plugin:
`https://commonsstaging.s3.amazonaws.com/uploads/sites/3/2019/05/IMG_3430.jpg`

In the S3 browser screenshot, the `standardweight-gradebook` image was uploaded on the main site and not `test2`.

I need to debug what is in the bucket so I can determine what can be done with the older Delicious Brains uploads.  The good thing is uploads made via Delicious Brains has a postmeta marker, so there is the potential to rewrite the DB URL to match the correct filepath.  I'll ping you for some more info that I'll need.

**Comment by r-a-y** [comment]
> The current pattern used by Delicious Brains is:
>
> https://s3.amazonaws.com/hwdsbcommons/wp-content/uploads/sites/12947/2019/03/image_name.jpeg
>
> where 12947 is the site ID.

12947 doesn't appear to be the site ID.  It appears to be some type of ID, but it's _not_ the site ID... I'll have to do some more investigating.

One way to ensure that Delicious Brains uploads will work with HM is to move all the Delicious Brains uploads to the expected HM directories in the S3 bucket... this would take forever due to the size of our multisite install.  Not sure if it would be possible to do this via a script.

This would fix the items in the WP Media Library, however this wouldn't solve the attachment URLs already in the post content because the attachment URLs are hardcoded and not dynamic.  I can make some educated guesses though and could probably write a WP-CLI script to do this, but the S3 file moving would have to occur first.

Will do some more research tomorrow.

**Comment by mrjarbenne** [comment]
> but it's not the site ID

Sorry about that. I made an assumption. We know what happens when you do that...

I worry about moving the items into where HM would expect to find them. Beyond the attachment URLs there are going to be other spaces where the link to resources uploaded to the media library are referenced or shared (For example, if I upload instructions to a blog, then post those links to our Sharepoint site.) Could lead to a bunch of broken links beyond the multisite network.

**Comment by binaryfire** [comment]
Hi guys! Sorry to drop in but thought my question might be relevant. Do you know if the "storage space quotas" that are set for each child site in the network dashboard are still calculated correctly? 

These quotas are essential for people hosting clients' sites on a multisite install. We were hoping to offload everything to S3 but weren't sure if would break this. And if it does, would it be possible to get the folder size via the S3 API and re-populate this value?

**Comment by mrjarbenne** [comment]
@menathor We haven't tested that yet. I do know that the setting is respected when using the Delicious Brains version of Offload Media, which supports Multisite.
